openapi: 3.1.0
x-stoplight:
  id: lmk3uxxhv1wok
info:
  title: Save Configurator Document Services
  description: "1. Document & Image Upload\r\n\r\nAllows business and offer teams to upload a wide range of documents and images.\r\nSupported file types include PDFs, Word documents, Excel sheets, and common image formats (JPEG, PNG, etc.).\r\nMetadata tagging for easy categorization (e.g., product ID, document type, version).\r\n\r\n2. Product Association\r\n\r\nEach uploaded asset is linked to a specific product or product variant.\r\nEnables quick lookup and filtering based on product identifiers.\r\n\r\n3. Secure Download Access\r\n\r\nFactory teams and end users can securely download relevant documents.\r\nAccess control ensures only authorized users can view or retrieve sensitive files.\r\n\r\n4. Support for Manufacturing & Documentation\r\n\r\nProvides easy access to critical documentation such as:\r\nOperation manuals\r\nCommissioning guides\r\nInstallation instructions\r\nTechnical specifications\r\nEnhances efficiency in manufacturing, assembly, and quality assurance processes."
  version: 1.0.0
  summary: This service will provide upload and download service
  contact:
    name: Vinod Bathula
    url: 'https//:www.se.com'
    email: vinod.bathula@se.com
tags:
  - name: Upload
    description: Upload Document
  - name: Download
    description: Download Document
paths:
  /offer-design/authoritative-data/document/upload:
    post:
      summary: Upload a document against ADS ID
      description: This is api to upload document
      operationId: uploadDocument
      tags:
        - Upload
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      parameters:
        - name: adsId
          in: query
          required: true
          schema:
            type: string
          description: ADS ID
        - name: fileName
          in: query
          required: true
          schema:
            type: string
          description: Uploading file name with extension
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: Invalid request
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-stoplight:
        id: dnsefvw3nji1j
    servers: []
    parameters: []
  /offer-design/authoritative-data/document/download:
    get:
      summary: Download all documents associated with ADS ID
      description: Downaload document
      operationId: downloadDocument
      tags:
        - Download
      parameters:
        - name: adsId
          in: query
          required: true
          schema:
            type: string
          description: ADS ID to download documents for
      responses:
        '200':
          description: Successful operation
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid request
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-stoplight:
        id: ny3ft3bsawul7
    parameters: []
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      x-stoplight:
        id: ok4zhsi4m9g2n
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
servers:
  - url: 'https://api.qa.se.com/v1/offer-design/document-service'
    description: QA
